autodock:
  children:
    k8s-hosts:
      vars:
        K8S_ANSIBLE_USER: k8s_user
      hosts:
        k8s1:
          ansible_host: 10.10.10.10
          ansible_user: "{{K8S_ANSIBLE_USER}}"
        k8s2:
          ansible_host: 10.10.10.10
          ansible_user: "{{K8S_ANSIBLE_USER}}"
