autodock:
  children:
    k8s-hosts:
      vars:
        K8S_ANSIBLE_USER: k8s_user
      hosts:
        k8s1:
          #ansible_host: 192.168.1.105
          ansible_connection: local
          type: server
          ansible_user: "{{K8S_ANSIBLE_USER}}"
        k8s2:
          ansible_host: 192.168.1.106
          type: agent
          ansible_user: "{{K8S_ANSIBLE_USER}}"
        k8s3:
          ansible_host: 192.168.1.107
          type: agent
          ansible_user: "{{K8S_ANSIBLE_USER}}"
