autodock:
  children:
    k8s_hosts:
      vars:
        K8S_ANSIBLE_USER: k8s_user
        JUPYTER_CONFIG: ../../rke2/jupyter/values.yaml
        AIRFLOW_CONFIG: ../../rke2/airlfow/values.yaml
      hosts:
        k8s1:
          #ansible_host: 192.168.1.105
          ansible_connection: local
          type: server
          ansible_user: "{{K8S_ANSIBLE_USER}}"
        k8s2:
          ansible_host: 192.168.1.106
          type: agent
          ansible_user: "{{K8S_ANSIBLE_USER}}"
        k8s3:
          ansible_host: 192.168.1.107
          type: agent
          ansible_user: "{{K8S_ANSIBLE_USER}}"
        # k8s1w:
        #   ansible_host: 192.168.1.248
        #   type: agent
        #   ansible_user: "{{K8S_ANSIBLE_USER}}"
        # k8s2w:
        #   ansible_host: 192.168.1.190
        #   type: agent
        #   ansible_user: "{{K8S_ANSIBLE_USER}}"
