---
- name: "Deploy Kubernetes"
  hosts: k8s_hosts

  tasks:
  - name: "Test"
    ansible.builtin.debug:
      msg: "hi"

  - name: "Include rke2-common"
    include_role:
      name: rke2-common

  - name: "Install rke2-server"
    include_role:
      name: rke2-server
    when: type == "server"

  - name: "Install rke2-server"
    include_role:
      name: rke2-agent
    when: type == "agent"