apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-autodock
spec:
  storageClassName: longhorn-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
