
## Jupyterhub Deployment
# Add chart
- name: Add jupyter charts repo
  community.kubernetes.helm_repository:
    name: jupyterhub
    repo_url: https://hub.jupyter.org/helm-chart/
    repo_state: present

# Create PVCs
- name: Create PVC for Jupyterhub Database
  kubernetes.core.k8s:
    state: present
    namespace: jupyterhub
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: jupyterhub-database
      spec:
        accessModes:
          - ReadWriteOnce
        resources: 
          requests:
            storage: 1Gi
        storageClassName: longhorn-storage

# Add secrets for Oauth

- name: Replace GitHub client ID and secret in values.yaml
  replace:
    path: "/home/k8s_user/compute-infrastructure/rke2/jupyter/values.yaml"
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regex: 'client_id: ".*"', replace: 'client_id: "{{ github_client_id }}"' }
    - { regex: 'client_secret: ".*"', replace: 'client_secret: "{{ github_client_secret }}"' }

- name: Deploy JupyterHub using Helm
  community.kubernetes.helm:
    name: jupyterhub
    chart_ref: jupyterhub/jupyterhub
    namespace: jupyterhub
    values_files: "/home/k8s_user/compute-infrastructure/rke2/jupyter/values.yaml"


## Airflow Deployment

- name: Add Airflow DB PVC
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', '/home/k8s_user/compute-infrastructure/rke2/airflow/postgresql-pvc.yaml') }}"

- name: Add Airflow Logs PVC
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', '/home/k8s_user/compute-infrastructure/rke2/airflow/pvc-logs.yaml') }}"
    namespace: jupyterhub

- name: Add Airflow DAG PVC
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', '/home/k8s_user/compute-infrastructure/rke2/airflow/pvc-dags.yaml') }}"
    namespace: jupyterhub

## 

- name: Add airlfow charts repo
  community.kubernetes.helm_repository:
    name: apache-airflow
    repo_url: https://airflow.apache.org
    repo_state: present

- name: Airflow Deploy
  community.kubernetes.helm:
    name: airflow
    chart_ref: apache-airflow/airflow
    namespace: jupyterhub
    values_files: "/home/k8s_user/compute-infrastructure/rke2/jupyter/values.yaml"



