- name: Check if Helm command is installed locally
  ansible.builtin.shell: hash helm
  delegate_to: 127.0.0.1
  run_once: true
  changed_when: false
  args:
    executable: "/bin/bash"

- name: Ensure Cert-Manager namespace exists
  community.kubernetes.k8s:
    state: present
    kind: Namespace
    name: kube-system

- name: Install Cert-Manager
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    namespace: kube-system

- name: Ensure MetalLB namespace exists
  community.kubernetes.k8s:
    state: present
    kind: Namespace
    name: metallb-system

- name: Install MetalLB with configuration via Helm
  community.kubernetes.helm:
    name: metallb
    chart_ref: metallb/metallb
    namespace: metallb-system
    values:
      extraManifests:
        - apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: first-pool
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.1.200-192.168.1.220
        - apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2-advertisement
            namespace: metallb-system
          spec:
            ipAddressPools:
              - first-pool

- name: Ensure Longhorn namespace exists
  community.kubernetes.k8s:
    state: present
    kind: Namespace
    name: longhorn-system

- name: Install Longhorn
  community.kubernetes.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    namespace: longhorn-system

- name: Ensure Longhorn storage directories exist
  file:
    path: /mnt/longhorn-storage
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create StorageClass for Longhorn
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: longhorn-storage
      provisioner: driver.longhorn.io
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      volumeBindingMode: Immediate
