- name: Check if Helm command is installed locally
  ansible.builtin.shell: hash helm
  delegate_to: 127.0.0.1
  run_once: true
  changed_when: false
  args:
    executable: "/bin/bash"

- name: Ensure Cert-Manager namespace exists
  community.kubernetes.k8s:
    state: present
    kind: Namespace
    name: kube-system
  delegate_to: localhost


- name: Install Cert-Manager
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    namespace: kube-system
  delegate_to: localhost

- name: Ensure MetalLB namespace exists
  community.kubernetes.k8s:
    state: present
    kind: Namespace
    name: metallb-system
  delegate_to: localhost

- name: Install MetalLB with configuration via Helm
  community.kubernetes.helm:
    name: metallb
    chart_ref: metallb/metallb
    namespace: metallb-system
    values:
      extraManifests:
        - apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: first-pool
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.1.200-192.168.1.220
        - apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2-advertisement
            namespace: metallb-system
          spec:
            ipAddressPools:
              - first-pool
  delegate_to: localhost

- name: Ensure Longhorn namespace exists
  community.kubernetes.k8s:
    state: present
    kind: Namespace
    name: longhorn-system
  delegate_to: localhost

- name: Install Longhorn
  community.kubernetes.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    namespace: longhorn-system
  delegate_to: localhost
