apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dags
spec:
  accessModes:
    - ReadWriteMany  # Allows multiple pods to access the volume
  resources:
    requests:
      storage: 1Gi  # Size of the volume
  storageClassName: longhorn-storage  # Specify your storage class
