dags:
  persistence:
    enabled: true  # Enable DAG persistence
    existingClaim: pvc-dags  # Reference an existing Persistent Volume Claim
    size: 10Gi  # Adjust the PVC size based on your needs
    accessMode: ReadWriteMany  # Ensure the access mode allows multiple pods to read/write

  gitSync:
    enabled: true  # Enable Git-Sync for syncing DAGs
    repo: "https://github.com/hwcopeland/airflow-dags"  # Public Git repository
    branch: "main"  # Branch to sync
    rev: "HEAD"  # Use HEAD for the latest commit
    wait: 300  # Sync interval (every 300 seconds)
    subPath: ""

logs:
  persistence:
    enabled: true  # Enable persistence for logs
    existingClaim: pvc-logs  # Reference an existing Persistent Volume Claim for logs

scheduler:
  waitForMigrations:
    enabled: False

webserver:
  labels:
    app: airflow
  waitForMigrations:
    enabled: False
  service:
    type: LoadBalancer  # Expose the webserver externally
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080

workers:
  replicas: 16
  waitForMigrations:
    enabled: False

triggerer:
  waitForMigrations:
    enabled: False

airflow:
  config:
    AIRFLOW_CORE_DAGS_FOLDER: /opt/airflow/dags/repo

postgresql:
    postgresqlExtendedConf:
      max_connections: 200
