dags:
  persistence:
    enabled: true
    existingClaim: pvc-dags
    size: 10Gi
    accessMode: ReadWriteMany

  gitSync:
    enabled: true
    repo: "https://github.com/hwcopeland/airflow-dags"
    branch: "main"
    rev: "HEAD"
    wait: 60
    subPath: ""

logs:
  persistence:
    enabled: true
    existingClaim: pvc-logs

scheduler:
  waitForMigrations:
    enabled: False

webserver:
  labels:
    app: airflow
  waitForMigrations:
    enabled: False
  service:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080

workers:
  waitForMigrations:
    enabled: False
  replicas: 4
  persistence:  # Corrected this line
    size: 10Gi  # Updated the size here

triggerer:
  waitForMigrations:
    enabled: False

airflow:
  config:
    AIRFLOW_CORE_DAGS_FOLDER: /opt/airflow/dags/repo

postgresql:
  postgresqlExtendedConf:
      max_connections: 200
