apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-storage
