hub:
  config:
    JupyterHub:
      authenticator_class: github
    GitHubOAuthenticator:
      client_id: "{{ github_client_id }}"
      client_secret: "{{ github_client_secret }}"
      oauth_callback_url: https://jupyter.hwcopeland.net/hub/oauth_callback
      allowed_organizations:
        - Khemiatic-Energistics
      scope:
        - read:org
  db:
    type: postgres  # Use 'postgres' for PostgreSQL
    pvc:
      storageClassName: "longhorn-storage"  # Your storage class (use Longhorn here)
      accessModes:
        - ReadWriteOnce
singleuser:
  storage:
    dynamic:
      pvcNameTemplate: claim-{username}{servername}
      storageClass: "longhorn-storage"  # Using Longhorn for dynamic user storage
      storageAccessModes: ["ReadWriteMany"]
    capacity: 2Gi  # Default capacity per user PVC
  extraEnv:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

